# Креды для доступа к API Regru, рекомендуется использовать отдельный пароль
# для этого создайте "альтернативный API-пароль" в настройках API
REGRU_USER="REGRU@EMAIL.RU"
REGRU_PASS="YOUR_PASS"
REGRU_ZONE="your.domen.com"

ACME_PROPAGATION_TIMEOUT=1800
ACME_PROPAGATION_INTERVAL=15

# Опционально. Если не заданы — уведомление уйдёт только в syslog.
TG_BOT_TOKEN='TOKEN'
TG_CHAT_ID='CHAT_ID_START_WITH_-100'
